### ISSUE TITLE
Missing documentation for shutdown hook

### ISSUE THREAD

**Issue by rachelvwood** [linkerd/website#1093]
A shutdown endpoint was added in [linkerd/linkerd2-proxy#811](https://github.com/linkerd/linkerd2-proxy/pull/811) to allow job pods to be terminated correctly.  I haven't found any documentation or examples on how to actually use this feature, so it would be nice if it could be added to the docs.  

The original problem is referenced in the [Linkerd graceful shutdown docs](https://linkerd.io/2.10/tasks/graceful-shutdown/#job-resources), but there isn't any information about the solution.

**Comment by wmorgan** [comment]
Thank you!

**Comment by hollowimage** [comment]
Until docs are formalized, can we get an example of this implementation somewhere in this thread?

**Comment by JoeAmedeo** [comment]
If you still need an example, this was what I was able to come up with. It looks like you can make a POST request to localhost:4191/shutdown from the job container to hit this endpoint. Here is a small example job.
```
apiVersion: batch/v1
kind: Job
metadata:
  name: proxy-shutdown
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: wait-and-shutdown
          image: curlimages/curl
          command:
            - "/bin/sh"
            - "-c"
            - "sleep 30 && curl -X POST http://localhost:4191/shutdown"
      restartPolicy: Never
```
