### ISSUE TITLE
Add a list of Linkerd extensions to website

### ISSUE THREAD

**Issue by mateiidavid** [linkerd/website#1105]
It would be great to keep a list of extensions to make it easier for the community to find what they are interested in, directly from the website. 

For me, there are two obvious places where this list could live:
* the website's [extensions page](https://linkerd.io/2.10/tasks/extensions/);
* [the linkerd/linkerd2 repo](https://github.com/linkerd/linkerd2).

Both places have their advantages and disadvantages; keeping a list on the website would make it easier to format and would make it more transparent to the community (or to people interested in the project). Having it in the repo makes it easier for community members to raise pull requests and add their own extensions to the list.

After an off-GitHub discussion with @alpeb, we might be able to do both! I propose the following:

1. In the linkerd2 repo, maintain a list of extensions in a doc -- this will allow people to contribute to the project, add their extension to the list and their name on the board of contributors :) 
2. Add this list to the extensions page on the website; if the source of truth is the repository list, then the website can update it after each PR (similar to how releases are being handled).

An example format: 

In the linkerd2 repo, add an `EXTENSIONS_LIST.yaml` to the root of the project.
```yaml
# EXTENSIONS_LIST.yaml
extensions:
  supported:
    - name: viz
      description: <...>
      repo_link: <...>
      doc_link: <...>
   ...
  thirdParty:
    - name: buyant-cloud
      description: <...>
      ...
    - name: tapshark
      ...
```

The list would split extensions into supported (maintained by the linkerd2 team) and 3rd party. Each extension would have a few attributes. I think the four included here (_name_, _description_, _repo link_, _doc link_) would suffice (with the repo/doc links being optional?).

The website's workflow could fetch the list from the repo (similar to how we pull in the latest version from the release page), add it under the data directory and then use the list to build a table in the extensions page.
