### ISSUE TITLE
"Bring your own Jaeger" page uses incorrect OT collector schema

### ISSUE THREAD

**Issue by m1o1** [linkerd/website#1335]
The ["Bring your own Jaeger" section](https://linkerd.io/2.11/tasks/distributed-tracing/#bring-your-own-jaeger) suggests the following config:
```
jaeger:
  enabled: false

collector:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      opencensus:
      zipkin:
      jaeger:
        protocols:
          grpc:
          thrift_http:
          thrift_compact:
          thrift_binary:
    processors:
      batch:
    extensions:
      health_check:
    exporters:
      jaeger:
        endpoint: my-jaeger-collector.my-jaeger-ns:14250
        insecure: true
    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp,opencensus,zipkin,jaeger]
          processors: [batch]
          exporters: [jaeger]
```
However, the proper schema for the jaeger exporter is:
```
jaeger:
  tls:
    insecure: true
```
