### ISSUE TITLE
Linkerd-viz: Update grafana setting when using 2.12.x 

### ISSUE THREAD

**Issue by hungran** [linkerd/website#1568]
https://github.com/linkerd/website/blob/main/linkerd.io/content/2.12/tasks/grafana.md?plain=1#L53-L74
The setting for grafana should be
```yaml
grafana.ini:
  server:
    root_url: '%(protocol)s://%(domain)s:%(http_port)s/grafana/'
    serve_from_sub_path: true
```

otherwise if don't using port
```yaml
grafana.ini:
  server:
    root_url: '%(protocol)s://%(domain)s:/grafana/'
    serve_from_sub_path: true
```
so the `grafana.url` should be below
```bash
linkerd viz install --set grafana.url=grafana.grafana \
  | kubectl apply -f -
```
doesn't need port
