### ISSUE TITLE
Generate CLI docs from code

### ISSUE THREAD

**Issue by grampelberg** [linkerd/website#164]
There's a great, structured way to show CLI commands and options now. This should be automatically generated by the Linkerd2 release process.

**Comment by lucperkins** [comment]
@grampelberg There *is* a way to generate YAML specs for CLI commands built into Cobra. I got it working yesterday. Here's an example for `linkerd check`:

```yaml
name: linkerd inject
synopsis: Add the Linkerd proxy to a Kubernetes config
description: |-
  Add the Linkerd proxy to a Kubernetes config.

  You can inject resources contained in a single file, inside a folder and its
  sub-folders, or coming from stdin.
options:
- name: api-port
  default_value: "8086"
  usage: Port where the Linkerd controller is running
- name: control-port
  default_value: "4190"
  usage: Proxy port to use for control
- name: disable-external-profiles
  default_value: "false"
  usage: Disables service profiles for non-Kubernetes services
- name: help
  shorthand: h
  default_value: "false"
  usage: help for inject
- name: image-pull-policy
  default_value: IfNotPresent
  usage: Docker image pull policy
- name: inbound-port
  default_value: "4143"
  usage: Proxy port to use for inbound traffic
- name: init-image
  default_value: gcr.io/linkerd-io/proxy-init
  usage: Linkerd init container image name
- name: linkerd-cni-enabled
  default_value: "false"
  usage: |
    Experimental: Omit the proxy-init container when injecting the proxy; requires the linkerd-cni plugin to already be installed
- name: linkerd-version
  shorthand: v
  default_value: dev-undefined
  usage: Tag to be used for Linkerd images
- name: metrics-port
  default_value: "4191"
  usage: Proxy port to serve metrics on
- name: outbound-port
  default_value: "4140"
  usage: Proxy port to use for outbound traffic
- name: proxy-cpu
  usage: Amount of CPU units that the proxy sidecar requests
- name: proxy-image
  default_value: gcr.io/linkerd-io/proxy
  usage: Linkerd proxy container image name
- name: proxy-log-level
  default_value: warn,linkerd2_proxy=info
  usage: Log level for the proxy
- name: proxy-memory
  usage: Amount of Memory that the proxy sidecar requests
- name: proxy-uid
  default_value: "2102"
  usage: Run the proxy under this user ID
- name: registry
  default_value: gcr.io/linkerd-io
  usage: Docker registry to pull images from
- name: skip-inbound-ports
  default_value: '[]'
  usage: |
    Ports that should skip the proxy and send directly to the application
- name: skip-outbound-ports
  default_value: '[]'
  usage: Outbound ports that should skip the proxy
- name: tls
  usage: 'Enable TLS; valid settings: "optional"'
inherited_options:
- name: api-addr
  usage: |
    Override kubeconfig and communicate directly with the control plane at host:port (mostly for testing)
- name: context
  usage: Name of the kubeconfig context to use
- name: kubeconfig
  usage: Path to the kubeconfig file to use for CLI requests
- name: linkerd-namespace
  shorthand: l
  default_value: linkerd
  usage: Namespace in which Linkerd is installed [$LINKERD_NAMESPACE]
- name: verbose
  default_value: "false"
  usage: Turn on debug logging
example: |2-
    # Inject all the deployments in the default namespace.
    kubectl get deploy -o yaml | linkerd inject - | kubectl apply -f -

    # Download a resource and inject it through stdin.
    curl http://url.to/yml | linkerd inject - | kubectl apply -f -

    # Inject all the resources inside a folder and its sub-folders.
    linkerd inject <folder> | kubectl apply -f -
see_also:
- linkerd - linkerd manages the Linkerd service mesh
```

There are two drawbacks to this approach:

* Some of the information that's currently included is not included here, namely the data type of the argument (e.g. `--namespace=string`), and an example argument (e.g. `--namespace=emojivoto`).
* It does add a layer of complexity because these YAML files would need to be generated from the CLI tool and committed to Git. For manual deploys, that could be fine.
