### ISSUE TITLE
Incorrect value in the deployment manifest example in the Configuring Proxy Concurrency task page in the Linkerd docs

### ISSUE THREAD

**Issue by southsidedean** [linkerd/website#1808]
On the documentation page for the Configuring Proxy Concurrency task (https://linkerd.io/2.15/tasks/configuring-proxy-concurrency/#), the CLI example is correct, using a `proxy-cpu-limit` of `2`, but the deployment manifest example is incorrect, with a `proxy-cpu-limit` of `1`.  Users who set the `proxy-cpu-limit` to `1` as shown in the deployment example will not have proxy concurrency.

The example manifest from the task page:

```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-deployment
  # ...
spec:
  template:
    metadata:
      annotations:
        config.linkerd.io/proxy-cpu-limit: '1'
  # ...
```

The page just needs a minor edit to change the `proxy-cpu-limit` value to `2` in the deployment example.
