### ISSUE TITLE
Document exposing dashboard/grafana via ingress

### ISSUE THREAD

**Issue by grampelberg** [linkerd/website#38]

**Comment by jakerobb** [comment]
This would be great!

**Comment by grampelberg** [comment]
The patch to make it work is:

```yaml
spec:
  template:
    spec:
      containers:
        - name: grafana
          env:
            - name: GF_SERVER_ROOT_URL
              value: "%(protocol)s://%(domain)s"
```

You can apply this via:

```bash
kubectl -n linkerd patch deploy grafana --patch "$(cat fix-grafana.yml)"
```

**Comment by ctaggart** [comment]
This worked! I have Linkerd web proxied using Ennoy Proxy. The relevant parts of the `enjoy.yaml` config:
``` yaml
                  - match: { prefix: "/dashboard/" }
                    route:
                      cluster: linkerd-grafana
                  - match: { prefix: "/d/" }
                    route:
                      cluster: linkerd-grafana
                  - match: { prefix: "/grafana/" }
                    route:
                      prefix_rewrite: "/"
                      cluster: linkerd-grafana
                  - match: { prefix: "/" }
                    route:
                      cluster: linkerd
```

Since `grafana` is at `/grafana`, my patch is:
``` yaml
spec:
  template:
    spec:
      containers:
        - name: grafana
          env:
            - name: GF_SERVER_ROOT_URL
              value: "%(protocol)s://%(domain)s/grafana"
```

And now that Linkerd 2.1 is out with the different service names, the command is now:
```
kubectl -n linkerd patch deploy linkerd-grafana --patch "$(cat fix-grafana.yml)"
```
