### ISSUE TITLE
Add debugging documentation

### ISSUE THREAD

**Issue by grampelberg** [linkerd/website#74]
- Proxy log level

**Comment by wmorgan** [comment]
@grampelberg can you expand on this a bit?

**Comment by grampelberg** [comment]
I'll need to spend some time on it. The proxy log level and some prometheus queries are all I've got right now as common troubleshooting techniques.

**Comment by grampelberg** [comment]
A simple debug container to help doing things like tcpdump.

```yaml
      - name: debug
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
          - |-
            while true; do sleep 100; done
```

```bash
apk add tcpdump
tcpdump -i any -s 65535 -w local.pcap
```
